import React, { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import Carousel from './Carousel'
import AIButton from './AIButton'
import AIResponsePanel from './AIResponsePanel'
import { api, LessonDetail, LessonSection } from '../services/api'
import './LessonContent.css'

const LessonContent: React.FC = () => {
  const { lessonId } = useParams<{ lessonId: string }>()
  const navigate = useNavigate()
  const [lessonData, setLessonData] = useState<LessonDetail | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [aiResponses, setAiResponses] = useState<Array<{
    id: string
    prompt: string
    response: string
    sectionTitle: string
    timestamp: Date
  }>>([])
  const [isGenerating, setIsGenerating] = useState(false)
  const [selectedConversationId, setSelectedConversationId] = useState<string | null>(null)

  useEffect(() => {
    const fetchLessonData = async () => {
      if (!lessonId) return
      
      try {
        setLoading(true)
        setError(null)
        const data = await api.getLessonDetail(lessonId)
        setLessonData(data)
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load lesson')
      } finally {
        setLoading(false)
      }
    }

    fetchLessonData()
  }, [lessonId])

  const handleAIPromptSubmit = async (prompt: string, sectionTitle: string) => {
    console.log(`AI prompt submitted for section "${sectionTitle}":`, prompt)
    
    setIsGenerating(true)
    
    try {
      // Here you would typically send the prompt to an AI service
      // For now, we'll simulate an AI response
      await new Promise(resolve => setTimeout(resolve, 2000))
      
      // Generate a mock AI response
      const mockResponse = generateMockAIResponse(prompt, sectionTitle)
      
      const newResponse = {
        id: Date.now().toString(),
        prompt,
        response: mockResponse,
        sectionTitle,
        timestamp: new Date()
      }
      
      setAiResponses(prev => [...prev, newResponse])
      // Auto-select the new conversation
      setSelectedConversationId(newResponse.id)
    } catch (error) {
      console.error('Error generating AI response:', error)
    } finally {
      setIsGenerating(false)
    }
  }


  const handleConversationSelect = (conversationId: string) => {
    setSelectedConversationId(conversationId)
  }

  const generateMockAIResponse = (prompt: string, sectionTitle: string): string => {
    const responses = [
      `That's a great question about ${sectionTitle.toLowerCase()}! Let me explain this in more detail...`,
      `I understand you're asking about ${sectionTitle.toLowerCase()}. Here's what you should know...`,
      `Excellent question! Regarding ${sectionTitle.toLowerCase()}, here's additional information...`,
      `That's an important aspect of ${sectionTitle.toLowerCase()}. Let me provide more context...`
    ]
    
    const randomResponse = responses[Math.floor(Math.random() * responses.length)]
    return `${randomResponse}\n\nThis is a mock AI response. In a real implementation, this would be generated by an AI service based on your prompt: "${prompt}"`
  }

  const handleBackClick = () => {
    navigate('/lessons')
  }

  const renderSectionContent = (section: LessonSection) => {
    if (typeof section.content === 'string') {
      return <p className="section-content">{section.content}</p>
    } else {
      // Handle array of steps
      return (
        <div className="stages-list">
          {section.content.map((step, index) => (
            <div key={index} className="stage-item">
              <span className="stage-number">{index + 1}.</span>
              <div className="stage-content">
                <strong>{step.step}:</strong> {step.description}
              </div>
            </div>
          ))}
        </div>
      )
    }
  }

  const renderSlides = () => {
    if (!lessonData) return []

    return lessonData.sections.map((section) => (
      <div key={section.id} className="lesson-section">
        <h2 className="section-title">{section.title}</h2>
        {renderSectionContent(section)}
        <AIButton 
          onSubmit={(prompt) => handleAIPromptSubmit(prompt, section.title)}
          sectionTitle={section.title}
        />
      </div>
    ))
  }

  if (loading) {
    return (
      <div className="lesson-layout">
        <div className="lesson-sidebar-left">
          <div className="question-history">
            <h4 className="question-history-title">
              <span className="question-history-icon">💬</span>
              Question History
            </h4>
            {aiResponses.length === 0 ? (
              <div className="question-history-empty">
                <div className="question-history-empty-icon">🤔</div>
                <div className="question-history-empty-text">
                  No questions asked yet. Use the AI buttons in the lesson content to get started!
                </div>
              </div>
            ) : (
              <ul className="question-history-list">
                {aiResponses.map((response) => (
                  <li 
                    key={response.id} 
                    className={`question-history-item ${selectedConversationId === response.id ? 'question-history-item-selected' : ''}`}
                    onClick={() => handleConversationSelect(response.id)}
                  >
                    <div className="question-history-header">
                      <span className="question-history-section">{response.sectionTitle}</span>
                      <span className="question-history-time">
                        {response.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </span>
                    </div>
                    <div className="question-history-text">{response.prompt}</div>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
        <div className="lesson-content">
          <button className="back-button" onClick={handleBackClick}>
            ← Back to Lessons
          </button>
          <div className="lesson-loading">
            <h1>Loading lesson...</h1>
            <p>Please wait while we fetch the lesson content.</p>
          </div>
        </div>
        <div className="lesson-sidebar-right">
          <AIResponsePanel
            responses={aiResponses}
            selectedConversationId={selectedConversationId}
            isGenerating={isGenerating}
          />
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="lesson-layout">
        <div className="lesson-sidebar-left">
          <div className="question-history">
            <h4 className="question-history-title">
              <span className="question-history-icon">💬</span>
              Question History
            </h4>
            {aiResponses.length === 0 ? (
              <div className="question-history-empty">
                <div className="question-history-empty-icon">🤔</div>
                <div className="question-history-empty-text">
                  No questions asked yet. Use the AI buttons in the lesson content to get started!
                </div>
              </div>
            ) : (
              <ul className="question-history-list">
                {aiResponses.map((response) => (
                  <li 
                    key={response.id} 
                    className={`question-history-item ${selectedConversationId === response.id ? 'question-history-item-selected' : ''}`}
                    onClick={() => handleConversationSelect(response.id)}
                  >
                    <div className="question-history-header">
                      <span className="question-history-section">{response.sectionTitle}</span>
                      <span className="question-history-time">
                        {response.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </span>
                    </div>
                    <div className="question-history-text">{response.prompt}</div>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
        <div className="lesson-content">
          <button className="back-button" onClick={handleBackClick}>
            ← Back to Lessons
          </button>
          <div className="lesson-error">
            <h1>Error Loading Lesson</h1>
            <p>{error}</p>
          </div>
        </div>
        <div className="lesson-sidebar-right">
          <AIResponsePanel
            responses={aiResponses}
            selectedConversationId={selectedConversationId}
            isGenerating={isGenerating}
          />
        </div>
      </div>
    )
  }

  if (!lessonData) {
    return (
      <div className="lesson-layout">
        <div className="lesson-sidebar-left">
          <div className="question-history">
            <h4 className="question-history-title">
              <span className="question-history-icon">💬</span>
              Question History
            </h4>
            {aiResponses.length === 0 ? (
              <div className="question-history-empty">
                <div className="question-history-empty-icon">🤔</div>
                <div className="question-history-empty-text">
                  No questions asked yet. Use the AI buttons in the lesson content to get started!
                </div>
              </div>
            ) : (
              <ul className="question-history-list">
                {aiResponses.map((response) => (
                  <li 
                    key={response.id} 
                    className={`question-history-item ${selectedConversationId === response.id ? 'question-history-item-selected' : ''}`}
                    onClick={() => handleConversationSelect(response.id)}
                  >
                    <div className="question-history-header">
                      <span className="question-history-section">{response.sectionTitle}</span>
                      <span className="question-history-time">
                        {response.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </span>
                    </div>
                    <div className="question-history-text">{response.prompt}</div>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
        <div className="lesson-content">
          <button className="back-button" onClick={handleBackClick}>
            ← Back to Lessons
          </button>
          <div className="lesson-not-found">
            <h1>Lesson Not Found</h1>
            <p>The lesson you're looking for doesn't exist.</p>
          </div>
        </div>
        <div className="lesson-sidebar-right">
          <AIResponsePanel
            responses={aiResponses}
            selectedConversationId={selectedConversationId}
            isGenerating={isGenerating}
          />
        </div>
      </div>
    )
  }

  const sectionTitles = lessonData.sections.map(section => section.title)

  return (
    <div className="lesson-layout">
      <div className="lesson-sidebar-left">
        <div className="question-history">
          <h4 className="question-history-title">
            <span className="question-history-icon">💬</span>
            Question History
          </h4>
          {aiResponses.length === 0 ? (
            <div className="question-history-empty">
              <div className="question-history-empty-icon">🤔</div>
              <div className="question-history-empty-text">
                No questions asked yet. Use the AI buttons in the lesson content to get started!
              </div>
            </div>
          ) : (
            <ul className="question-history-list">
              {aiResponses.map((response) => (
                <li 
                  key={response.id} 
                  className={`question-history-item ${selectedConversationId === response.id ? 'question-history-item-selected' : ''}`}
                  onClick={() => handleConversationSelect(response.id)}
                >
                  <div className="question-history-header">
                    <span className="question-history-section">{response.sectionTitle}</span>
                    <span className="question-history-time">
                      {response.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                  </div>
                  <div className="question-history-text">{response.prompt}</div>
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>
      
      <div className="lesson-content">
        <button className="back-button" onClick={handleBackClick}>
          ← Back to Lessons
        </button>
        <Carousel sectionTitles={sectionTitles}>
          {renderSlides()}
        </Carousel>
      </div>
      
      <div className="lesson-sidebar-right">
        <AIResponsePanel
          responses={aiResponses}
          selectedConversationId={selectedConversationId}
          isGenerating={isGenerating}
        />
      </div>
    </div>
  )
}

export default LessonContent
